version: '3.9'
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - '7788:7788'
    container_name: web-app
    depends_on:
      - db
    networks:
      - postgres
  db:
    image: postgres
    volumes:
      - ./pinkTeam:/var/lib/postgresql/data
    container_name: pinkTeam
    env_file: ./.env
    ports:
      - '5432:5432'
    networks:
      - postgres
volumes:
  pinkTeam:
networks:
  postgres:
    driver: bridge