version: '3.9'
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - '7788:7788'
    container_name: rubbish-app
    depends_on:
       - db
    networks:
      - postgres
  db:
    image: postgres
    volumes:
      - ./pink:/var/lib/postgresql/data
    container_name: pinkTeam-data
    env_file:
       - ./.env
    ports:
      - '5432:5432'
    networks:
      - postgres
volumes:
  pinkTeam:

networks:
  postgres:
    driver: bridge